### ISSUE TITLE
Iss-domo password

### ISSUE THREAD

**Issue by anthony13011** [bobinou/iss-domo#3]
Hello, 

Thanks for your application which works wonderfully great !!! 

However, can you tell me how can we make an user access password ? 

Thanks a lot.

**Comment by Cosaque** [comment]
same i try since 3hour to put a simple http login / password to secure communication with Iss-domo & Imperihome

**Comment by bobinou** [comment]
Il you want ton secure access ton iss-domo, you can use Nginx service.

1. Install Nginx
2. Integration d'ISS-Domo a NGinx

Placer ISS-Domo dans le repertoire /usr/share/nginx/www/ s'il est dans /var/www/

sudo cp -R /var/www/iss-domo/ /usr/share/nginx/www/
Donner les droits 777 au repertoire iss-domo

sudo chmod -R 777 /usr/share/nginx/www/iss-domo/
Editer le fcihier /etc/nginx/sites-enabled/default

sudo nano /etc/nginx/sites-enabled/default
Ajouter les lignes suivantes AVANT la location /jeedom

location /iss-domo/public/ {

try_files $uri $uri/ @rewrite;

}

location @rewrite {

rewrite ^/(?<appname>[^/]+)/public/(?<appurl>.+)$ /$appname/public/index.php?_url=/$appurl last;

}

Redemarrer Nginx

ISS-Domo est alors accessible depuis Imperihome à l'adresse http://IP-server-iss-domo/iss-domo/public

3. Sécurisation de l'accès à ISS-Domo

Editer le fichier /etc/nginx/sites-enabled/default

sudo nano /etc/nginx/sites-enabled/default
Ajouter les lignes suivantes dans la section location /iss-domo/public/ { :

auth_basic "Restricted Access";

auth_basic_user_file /usr/share/nginx/www/iss-domo/app/config/.htpasswd;

Redemarrer Nginx

sudo /etc/init.d/nginx restart
L'accès à Iss-domo se fait toujours sur l'url http://IP-server-iss-domo/iss-domo/public.

Le login est iss-domo et le mot de passe iss-domo.

Les accès peuvent etre modifiés en éditant le fichier /usr/share/nginx/www/iss-domo/app/config/.htpasswd

sudo nano /usr/share/nginx/www/iss-domo/app/config/.htpasswd

**Comment by Cosaque** [comment]
ok je viens de terminer et ca fonctionne en fait j'ai fais un peu différamment :)
1) mon infra : 
j'utilise 1 synology DS414 avec domoticz (en package) installé dessus
j'ai installé iss-domo dessus également et je le lance avec "php artisan serve --host 192.168.0.17 &"
car il semble que je ne puisse pas installer lsb-base
./iss-domo.sh start
E: /lib/lsb/init-functions not found, lsb-base (>= 3.0-6) needed

2) ce que j'ai fais
sur les syno c'est apache qui est installé par défault j'utilise donc celui-ci a la place de Nginx
d'ordinaire j'utilise des reverse proxy afin de me connecter sur mes sites sans avoir a saisir le port, j'ai donc juste eu a rajouter la sécurité dans la conf du vhost ca donne un truc comme ca : 

<VirtualHost *:443>
  ServerName domo.domaine.fr
  Header always append X-Frame-Options SAMEORIGIN
  ProxyRequests Off
  ProxyVia Off
    <Proxy *>
     Order deny,allow
     Allow from all
     AuthUserFile /chemin/security/.htpasswd
     AuthGroupFile /dev/null
     AuthName "Accès sécurisé au site ISS-domo"
     AuthType Basic
     Require valid-user
    </Proxy>
  ProxyPass / http://192.168.0.x:8000/
  ProxyPassReverse / http://192.168.0.x:8000/
</VirtualHost>

Merci en tout cas d'avoir pris le temps de me répondre :)
je vais donc pouvoir utiliser de manière sécurisé Imperihome pour gérer mon installation zwave depuis l'extèrieur !
